language: python
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/user_management'
    - TERM='xterm-256color'
  matrix:
    - TOX_ENV=py27-django110
    - TOX_ENV=py34-django110
    - TOX_ENV=py35-django110
    - TOX_ENV=py27-djangopre
    - TOX_ENV=py34-djangopre
    - TOX_ENV=py35-djangopre
matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djangopre
    - env: TOX_ENV=py34-djangopre
    - env: TOX_ENV=py35-djangopre
install:
  - psql -c 'CREATE DATABASE user_management' -U postgres;
  - pip install -U pip
  - pip install tox==1.9.0 coveralls
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
notifications:
  email: false
